# Table of Contents
1. [Introduction to NumPy](#1)
   * [1.1. What is NumPy?](#1.1)
   * [1.2. NumPy Installation](#1.2)


2. [NumPy Arrays](#2)
   * [2.1. Basics of NumPy Arrays](#2.1)
   * [2.2. Key Advantages of NumPy Arrays](#2.2)
   * [2.3. Creating Arrays from Lists](#2.3)
   * [2.4. Using NumPy Functions to Create Arrays](#2.4)


3. [Array Indexing and Slicing](#3)
   * [3.1. Indexing and Slicing Basics](#3.1)
   * [3.2. Multidimensional Array Indexing](#3.2)


4. [Array Shape and Reshaping](#4)
   * [4.1. Reshaping Arrays](#4.1)
   
   
5. [Array Data Types](#5)
   * [5.1. Data Types in NumPy](#5.1)
   * [5.2. Specifying Data Types](#5.2)


6. [Array Operations](#6)
   * [6.1. Basic Arithmetic Operations](#6.1)
   * [6.2. Element-Wise Operations](#6.2)
   * [6.3. Mathematical Functions in NumPy](#6.3)
   * [6.4. Broadcasting in Mathematical Operations](#6.4)
   
   
7. [Aggregation Functions](#7)
   * [7.1. Sum, Mean, Median, etc.](#7.1)
   * [7.2. Aggregation Along Specified Axes](#7.2)
   * [7.3. Custom Functions on Arrays](#7.3)


8. [Sorting and Searching](#8)
   * [8.1. Sorting Arrays](#8.1)
   * [8.2. Searching for Elements](#8.2)

9. [Boolean Indexing](#9)
   * [9.1. Filtering with Boolean Conditions](#9.1)
   * [9.2. Combining Conditions](#9.2)


10. [Element-Wise Conditional Operations](#10)
   * [10.1. Conditional Operations using NumPy](#10.1)
   * [10.2. Replacing Values Based on Conditions](#10.2)


11. [Array Manipulation](#11)
   * [11.1. Joining Arrays](#11.1)
   * [11.2. Splitting Arrays](#11.2)
   * [11.3. Adding and Removing Elements from Arrays](#11.3)


12. [Transposing Arrays](#12)
   * [12.1. Transposing for Data Transformations](#12.1)
   * [12.2. Transposing for Matrix Multiplication](#12.2)


13. [File I/O](#13)
   * [13.1. Loading and Saving Data](#13.1)
   * [13.2. CSV and Text Files](#13.2)
   
   
14. [Binary Files](#14)
   * [14.1. Reading and Writing Binary Files](#14.1)


15. [Linear Algebra with NumPy](#15)
   * [15.1. Matrix Multiplication](#15.1)
   * [15.2. Determinants and Inverses](#15.2)
   * [15.3. Eigenvalues and Eigenvectors](#15.3)


16. [Random Number Generation](#16)
   * [16.1. Random Sampling](#16.1)
   * [16.2. Seed and Reproducibility](#16.2)


17. [Advanced NumPy Topics](#17)
   * [17.1. Structured Arrays](#17.1)
   * [17.2. Memory Views](#17.2)
   * [17.3. Universal Functions (Ufuncs)](#17.3)
   * [17.4. Custom Data Types](#17.4)

<a id = "1"></a>
# 1. Introduction to NumPy

<a id = "1.1"></a>
### 1.1. What is NumPy?
NumPy is the fundamental library for scientific computing in Python. It provides support for arrays and matrices as well as a large collection of high-level mathematical functions to operate on these arrays. NumPy is open-source and is widely used in various scientific and engineering disciplines.

<a id = "1.2"></a>
### 1.2. NumPy Installation
To install NumPy, you can use pip. Open the terminal or command prompt and enter the following command:

In [1]:
pip install numpy

import numpy as np    # Verify if NumPy is correctly installed by importing it in Python
print(np.__version__) # This code should print the version of NumPy if the installation was successful.

1.23.5


<a id = "2"></a>
# 2. NumPy Arrays

<a id = "2.1"></a>
### 2.1. Basics of NumPy Arrays
NumPy arrays are homogeneous, multidimensional data structures that allow you to store and manipulate large datasets efficiently. They are similar to Python lists but have some key advantages.

<a id = "2.2"></a>
### 2.2. Key Advantages of NumPy Arrays
- Efficiency: NumPy arrays are more memory-efficient and faster for numerical operations than Python lists.
- Homogeneity: NumPy arrays contain elements of the same data type which allows for better optimization.
- Multidimensionality: NumPy supports multi-dimensional arrays, making it ideal for scientific computations.

<a id = "2.3"></a>
### 2.3. Creating Arrays from Lists
You can create NumPy arrays from Python lists using the `array()` function.

In [2]:
my_list = [1, 2, 3, 4, 5]
my_array = np.array(my_list)

print(my_array)

[1 2 3 4 5]


<a id = "2.4"></a>
### 2.4. Using NumPy Functions to Create Arrays
NumPy provides various functions for creating arrays such as `np.zeros()`, `np.ones()` and `np.arange()`.

In [3]:
zeros_array = np.zeros(5)
ones_array = np.ones(5)
range_array = np.arange(1, 11)

print(zeros_array, ones_array, range_array)

[0. 0. 0. 0. 0.] [1. 1. 1. 1. 1.] [ 1  2  3  4  5  6  7  8  9 10]


<a id = "3"></a>
# 3. Array Indexing and Slicing

<a id = "3.1"></a>
### 3.1. Indexing and Slicing Basics
NumPy arrays can be accessed using square brackets similar to Python lists. Indexing starts at 0 and negative indices count from the end.

In [4]:
my_array = np.array([0, 1, 2, 3, 4, 5])

first_element = my_array[0]  # Access the first element
last_element = my_array[-1]  # Access the last element

print(first_element, last_element)

0 5


<a id = "3.2"></a>
### 3.2. Multidimensional Array Indexing
You can index multi-dimensional arrays using multiple indices separated by commas.

In [5]:
my_matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
element = my_matrix[1, 2]  # Access the element in the second row, third column

print(element)

6


<a id = "4"></a>
# 4. Array Shape and Reshaping
The shape of a NumPy array is a tuple indicating the size of each dimension. You can access the shape using the `.shape` attribute.

In [6]:
my_array = np.array([[1, 2, 3], [4, 5, 6]])
shape = my_array.shape

print(shape)

(2, 3)


<a id = "4.1"></a>
### 4.1. Reshaping Arrays
You can change the shape of an array using the `.reshape()` method.

In [7]:
my_array = np.array([1, 2, 3, 4, 5, 6])
reshaped_array = my_array.reshape(2, 3)

print(reshaped_array)

[[1 2 3]
 [4 5 6]]


<a id = "5"></a>
# 5. Array Data Types

<a id = "5.1"></a>
### 5.1. Data Types in NumPy
NumPy arrays are homogeneous, meaning all elements have the same data type. Common data types include `int`, `float`, and `complex`.

In [8]:
integer_array = np.array([1, 2, 3], dtype=int)
float_array = np.array([1.0, 2.0, 3.0], dtype=float)

<a id = "5.2"></a>
### 5.2. Specifying Data Types
You can explicitly specify the data type when creating an array.

In [9]:
my_array = np.array([1, 2, 3], dtype=float)

<a id = "6"></a>
# 6. Array Operations

<a id = "6.1"></a>
### 6.1. Basic Arithmetic Operations
NumPy arrays support basic arithmetic operations like addition, subtraction, multiplication and division.

In [10]:
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

sum_array = array1 + array2    
difference_array = array1 - array2
product_array = array1 * array2
quotient_array = array1 / array2

print(sum_array)
print(difference_array)
print(product_array)
print(quotient_array)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


<a id = "6.2"></a>
### 6.2. Element-Wise Operations
Arithmetic operations on NumPy arrays are performed element-wise, meaning each element is operated on individually.

In [11]:
array = np.array([1, 2, 3])

square_root_array = np.sqrt(array)
square_array = np.square(array)  # Square each element
absolute_array = np.abs(array)  # Absolute value of each element

print(square_root_array)
print(square_array)
print(absolute_array)

[1.         1.41421356 1.73205081]
[1 4 9]
[1 2 3]


<a id = "6.3"></a>
### 6.3. Mathematical Functions in NumPy
NumPy provides a wide range of mathematical functions for arrays.

In [12]:
array = np.array([1, 2, 3])

mean_value = np.mean(array)
standard_deviation = np.std(array)
logarithm = np.log(array)
exponential = np.exp(array)

print(mean_value)
print(standard_deviation)
print(logarithm)
print(exponential)

2.0
0.816496580927726
[0.         0.69314718 1.09861229]
[ 2.71828183  7.3890561  20.08553692]


<a id = "6.4"></a>
### 6.4. Broadcasting in Mathematical Operations
NumPy automatically broadcasts arrays of different shapes during arithmetic operations.

In [13]:
array1 = np.array([1, 2, 3])
array2 = np.array([2])

result = array1 + array2  # Broadcasting: [1+2, 2+2, 3+2]

<a id = "7"></a>
# 7. Aggregation Functions

<a id = "7.1"></a>
### 7.1. Sum, Mean, Median, etc.
NumPy offers aggregation functions for summarizing array data.

In [14]:
array = np.array([1, 2, 3, 4, 5])

total_sum = np.sum(array)
mean_value = np.mean(array)
median_value = np.median(array)

print(total_sum)
print(mean_value)
print(median_value)

15
3.0
3.0


<a id = "7.2"></a>
### 7.2. Aggregation Along Specified Axes
You can aggregate along specific axes in multi-dimensional arrays.

In [15]:
matrix = np.array([[1, 2, 3], [4, 5, 6]])

row_sum = np.sum(matrix, axis=1)  # Sum along rows
column_mean = np.mean(matrix, axis=0)  # Mean along columns

print(row_sum)
print(column_mean)

[ 6 15]
[2.5 3.5 4.5]


<a id = "7.3"></a>
### 7.3. Custom Functions on Arrays
You can also apply custom functions element-wise using `np.vectorize()` function.

In [16]:
array = np.array([1, 2, 3])

# Define a custom function
def custom_function(x):
    return x * 2

custom_function_vectorized = np.vectorize(custom_function)
result = custom_function_vectorized(array)

print(result)

[2 4 6]


<a id = "8"></a>
# 8. Sorting and Searching

<a id = "8.1"></a>
### 8.1. Sorting Arrays
NumPy provides functions for sorting arrays.

In [17]:
array = np.array([3, 1, 2, 5, 4])

sorted_array = np.sort(array)  # Sort in ascending order
argsort_array = np.argsort(array)  # Get indices that would sort the array

print(sorted_array)
print(argsort_array)

[1 2 3 4 5]
[1 2 0 4 3]


<a id = "8.2"></a>
### 8.2. Searching for Elements
You can search for elements in arrays using functions like `np.where()`.

In [18]:
array = np.array([1, 2, 3, 4, 5])
indices = np.where(array == 3)  # Find indices where value is 3

print(indices)

(array([2]),)


<a id = "9"></a>
# 9. Boolean Indexing

<a id = "9.1"></a>
### 9.1. Filtering with Boolean Conditions
Boolean indexing enables you to filter an array based on a condition.

In [19]:
array = np.array([1, 2, 3, 4, 5])

condition = array > 2
filtered_array = array[condition]  # Get elements greater than 2

print(filtered_array)

[3 4 5]


<a id = "9.2"></a>
### 9.2. Combining Conditions
You can combine multiple conditions using logical operators.

In [20]:
array = np.array([1, 2, 3, 4, 5])

condition1 = array > 2
condition2 = array < 5

combined_condition = np.logical_and(condition1, condition2)
filtered_array = array[combined_condition]  # Get elements between 2 and 4

<a id = "10"></a>
# 10. Element-wise Conditional Operations

<a id = "10.1"></a>
### 10.1. Conditional operations using NumPy
NumPy supports conditional operations to create arrays based on specified conditions.

In [21]:
array = np.array([1, 2, 3, 4, 5])

condition = array > 2
result = np.where(condition, array, 0)  # Replace elements greater than 2 with 0

print(result)

[0 0 3 4 5]


<a id = "10.2"></a>
### 10.2. Replacing Values Based on Conditions
You can replace elements in an array based on conditions.

In [22]:
array = np.array([1, 2, 3, 4, 5])

array[array > 2] = 0  # Replace elements greater than 2 with 0

print(array)

[1 2 0 0 0]


<a id = "11"></a>
# 11. Array Manipulation
NumPy provides functions to join and split arrays efficiently.

<a id = "11.1"></a>
### 11.1. Joining Arrays
You can concatenate or stack arrays using functions like `np.concatenate()`, `np.vstack()`, and `np.hstack()`.

In [23]:
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

concatenated_array = np.concatenate((array1, array2))
vertical_stack = np.vstack((array1, array2))
horizontal_stack = np.hstack((array1, array2))

print(concatenated_array)
print(vertical_stack)
print(horizontal_stack)

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


<a id = "11.2"></a>
### 11.2. Splitting Arrays
You can split arrays using `np.split()` and related functions.

In [24]:
array = np.array([1, 2, 3, 4, 5, 6])
split_arrays = np.split(array, 3)  # Split into 3 equal parts

print(split_arrays)

[array([1, 2]), array([3, 4]), array([5, 6])]


<a id = "11.3"></a>
### 11.3. Adding and Removing Elements from Arrays
You can add and remove elements from arrays using functions like `np.append()`, `np.insert()` and `np.delete()`.

In [25]:
array = np.array([1, 2, 3, 4, 5])   
print("Original Array = ", array)

array = np.append(array, [6, 7])    # Add elements to the end of the array
print(array)

array = np.insert(array, 2, [8, 9]) # Insert elements at specific positions
print(array)

array = np.delete(array, [0, 1])    # Delete elements at specific positions
print(array)

Original Array =  [1 2 3 4 5]
[1 2 3 4 5 6 7]
[1 2 8 9 3 4 5 6 7]
[8 9 3 4 5 6 7]


<a id = "12"></a>
# 12. Transposing Arrays

<a id = "12.1"></a>
### 12.1. Transposing for Data Transformations
You can transpose arrays to exchange rows with columns or reshape data.

In [26]:
matrix = np.array([[1, 2, 3], [4, 5, 6]])
transposed_matrix = np.transpose(matrix)

print(transposed_matrix)

[[1 4]
 [2 5]
 [3 6]]


<a id = "12.2"></a>
### 12.2. Transposing for Matrix Multiplication
Transposing is often used for matrix multiplication.

In [27]:
matrix1 = np.array([[1, 2, 3], [4, 5, 6]])
matrix2 = np.array([[7, 8], [9, 10], [11, 12]])

result_matrix = np.dot(matrix1, matrix2)

print(result_matrix)

[[ 58  64]
 [139 154]]


<a id = "13"></a>
# 13. File I/O

<a id = "13.1"></a>
### 13.1. Loading and Saving Data
NumPy provides functions to read and write arrays from/to files.

In [28]:
array = np.array([1, 2, 3, 4, 5])      
np.savetxt('data.txt', array)   # Save an array to a text file

loaded_array = np.loadtxt('data.txt')  # Load an array from a text file

<a id = "13.2"></a>
### 13.2. CSV and Text Files
You can also read and write data in CSV and text file formats using NumPy.

In [29]:
array = np.array([[1, 2, 3], [4, 5, 6]])     
np.savetxt('data.csv', array, delimiter=',')  # Save an array to a CSV file

loaded_array = np.genfromtxt('data.csv', delimiter=',')   # Load an array from a CSV file

<a id = "14"></a>
# 14. Binary Files

<a id = "14.1"></a>
## 14.1. Reading and Writing Binary Files
NumPy supports saving and loading arrays in binary format.

In [30]:
array = np.array([1, 2, 3, 4, 5])    # Save an array to a binary file
np.save('data.npy', array)

loaded_array = np.load('data.npy')   # Load an array from a binary file

<a id = "15"></a>
# 15. Linear Algebra with NumPy

<a id = "15.1"></a>
### 15.1. Matrix Multiplication
NumPy provides efficient matrix multiplication using the `np.dot()` function.

In [31]:
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])

result_matrix = np.dot(matrix1, matrix2)

print(result_matrix)

[[19 22]
 [43 50]]


<a id = "15.2"></a>
### 15.2. Determinants and Inverses
You can compute the determinant and inverse of a matrix using NumPy.

In [32]:
matrix = np.array([[1, 2], [3, 4]])

determinant = np.linalg.det(matrix)
inverse_matrix = np.linalg.inv(matrix)

print(determinant)
print(inverse_matrix)

-2.0000000000000004
[[-2.   1. ]
 [ 1.5 -0.5]]


<a id = "15.3"></a>
### 15.3. Eigenvalues and Eigenvectors
NumPy allows you to calculate eigenvalues and eigenvectors of a matrix.

In [33]:
matrix = np.array([[1, 2], [2, 1]])

eigenvalues, eigenvectors = np.linalg.eig(matrix)

<a id = "16"></a>
# 16. Random Number Generation

<a id = "16.1"></a>
### 16.1. Random Sampling
NumPy provides functions for generating random numbers and samples.

In [34]:
random_integers = np.random.randint(1, 100, size=5)  # Generate random integers within a range
random_uniform = np.random.uniform(0, 1, size=5)     # Generate random numbers from a uniform distribution
random_normal = np.random.normal(0, 1, size=5)       # Generate random numbers from a normal distribution

<a id = "16.2"></a>
### 16.2. Seed and Reproducibility
You can set a seed to ensure reproducibility of random number generation.

In [35]:
np.random.seed(42)
random_numbers = np.random.rand(5)

<a id = "17"></a>
# 17. Advanced NumPy Topics

<a id = "17.1"></a>
### 17.1. Structured Arrays
Structured arrays allow you to work with heterogeneous data types within a single array. This is useful for handling structured data like CSV files or database records.

In [36]:
data = np.array([(1, 'Alice', 25), (2, 'Bob', 30)], dtype=[('id', 'i4'), ('name', 'U10'), ('age', 'i4')])
print(data)

[(1, 'Alice', 25) (2, 'Bob', 30)]


<a id = "17.2"></a>
### 17.2. Memory Views
Memory views provide a way to access and manipulate the memory of an array without making a copy of the data.

In [37]:
array = np.array([1, 2, 3, 4, 5])
memory_view = memoryview(array)

print(memory_view)

<a id = "17.3"></a>
### 17.3. Universal Functions (Ufuncs)
Universal functions (ufuncs) are functions that operate element-wise on arrays, making them efficient for numerical operations.

In [38]:
array = np.array([1, 2, 3, 4, 5])

square_array = np.square(array)
log_array = np.log(array)

print(square_array)
print(log_array)

[ 1  4  9 16 25]
[0.         0.69314718 1.09861229 1.38629436 1.60943791]


<a id = "17.4"></a>
### 17.4. Custom Data Types
You can create custom data types for NumPy arrays to handle specialized data structures.

In [39]:
custom_dtype = np.dtype([('name', 'U10'), ('age', 'i4')])
data = np.array([('Alice', 25), ('Bob', 30)], dtype=custom_dtype)

print(data)

[('Alice', 25) ('Bob', 30)]
